INSERT INTO characterhooks VALUES
('blessed with good luck', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('cursed by the gods', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('cursed with bad luck', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('cursed with good luck', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('escaping the past', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('from a good family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('from a loathed family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('from an unusual family line', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('from nowhere', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('haunted by dark memories', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('hiding a dark secret', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('living on borrowed time', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('looking for love', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('needing a friend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('on the run from the law', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('on the wrong side of the law', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('searching for justice', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('searching for love', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('trapped by the past', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who can''t resist a fight', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who fears people think [they] is a fraud', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who fell in with the wrong crowd', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who had a near-death experience', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who had a near-death experience that changed [them] significantly', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has an alter ego', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has an arch-enemy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has an odd way of speaking', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who hates animals', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who hates children', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who hates the government', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a complete fraud', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a jack of all trades', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a loose cannon', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is an undercover agent', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is barking up the wrong tree', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is being blackmailed', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is considered the worst in [their] profession', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is dependent on medication', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is estranged from family members', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is given to moments of deep introspection', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is helping the local community', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is just a cog in the machine', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is keeping [their] mouth shut', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is keeping something at bay', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is more than meets the eye', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is prone to odd statements', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is searching for employment', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is struggling between good and evil', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is stubborn as a mule', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the life and soul of the party', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is thinking of retiring', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is ugly as sin', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lost a close friend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lost meaning in life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who loves animals', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who loves children', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who prefers to work alone', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who recently betrayed [their] faith', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who seems insane', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who looks very suspect', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who spent part of [their] life in prison', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who suffers from a chronic medical condition', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a bright future ahead', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a chemical dependency', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a criminal mind', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a dark past', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a false identity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a grim future ahead', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a heart of gold', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a knack for trouble', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a lot of friends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a lovely smile', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a terrible poker face', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a thirst for knowledge', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a thirst for vengeance', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a very tight schedule', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a weird superpower', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an extraordinary wealth', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an obsessive desire for power', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an odd birthmark', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an odd tattoo', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an unexpected destiny', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an unusual child', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an unusual spouse', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with big dreams', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with little money', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a mental illness', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with no friends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with no hope', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with repressed memories', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with suicidal thoughts', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with unconventional clothing', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who wants to change the world', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose heart is broken', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who wants to redeem [their] family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a sexy body', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a weird body', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is very famous', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is despised in the community', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who can''t read', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who wrote a book', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who hates the wilderness', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who loves the wilderness', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is perfectly normal', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a huge obsession', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an identical twin', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a second family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was falsely accused of a crime', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who gambles a lot', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a self taught martial artist', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who always arrives late', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who always arrives early', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who thinks [they] saw an alien', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose face is badly scarred', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an animal friend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a hidden agenda', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is very proud of [their] own race', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who refuses to call people by their own name', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who only works part-time', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who mysteriously wanders at night', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who never wears underwear', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is very attached to tradition', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who likes to be domineering', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a very successful business', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with an unsuccessful business', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who fought in a war', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who only wants to feel appreciated', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who hates crowds', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who does daily workouts', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who will never be as good as [their] predecessor', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who outclasses [their] predecessor', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a tyrannical master', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a boring life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a conventional life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a secret romantic relationship', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who schemes in the shadows', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a best friend from far away', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is an adventurer for hire', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was adopted', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who takes care of [their] family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a talented singer', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with three parents', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who recently lost a close friend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a childhood trauma', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who travels a lot', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who almost never leaves [their] house', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who believes in strange conspiracy theories', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who grows [their] own food', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a hoarding disorder', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a lot of issues', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is an expert in astrology', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who designs [their] own clothes', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lives inside [their] head', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who likes to have guests', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who hates foreigners', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has been publicly shamed', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is admired by many', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is very old fashioned', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who embraces innovation', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is afraid of death', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who believes in destiny', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who loves to give public speeches', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who drinks a lot', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with sinister morals', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with pure thoughts', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who endeavors to solve philosophical dilemmas', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with gastrointestinal issues', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with political ambitions', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who admires a local hero', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who can''t control [them]self', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is very perverted', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who got married more than once', '{"compatibleAges": ["adult", "middle-aged", "elderly", "venerable"]}'),
('from a privileged family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who recently moved to a new house', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who unintentionally hurt someone', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is also a collectionist', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with lots of jewelry', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has witnessed a crime', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was promised wealth and fame', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who goes on vacation often', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a deadly allergy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a valuable family heirloom', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who cares for the environment', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who doesn''t care for the environment', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is really a robot in disguise', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is seeking redemption', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is silently judging everyone', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is struggling with addiction', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the black sheep of the family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the last of [their] kind', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the only survivor of a tragedy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the victim of mistaken identity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is trying to make amends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is unsure of [their] true identity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is wanted dead or alive', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who keeps having prophetic dreams', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who left everything behind to pursue a dream', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lost everything in a natural disaster', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who made a deal with the devil', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who never backs down from a challenge', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who never forgets a face', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who never speaks the truth', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who ran away from home at a young age', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who sees ghosts', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who seeks revenge for a past betrayal', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who seems average but has a hidden talent', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who talks to imaginary friends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was abandoned as a child', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was betrayed by someone [they] trusted', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was once a hero but now a villain', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was once wealthy but lost everything', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who wishes to be immortal', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the lookout for danger', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s constantly plagued with bad luck', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s haunted by the ghosts of [their] enemies', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s known for [their] terrible cooking', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s searching for a lost artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s seeking [their] true purpose', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who struggles with social anxiety', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who possesses a mysterious and ancient artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s on a quest for knowledge', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has a love-hate relationship with [their] powers', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who believes [they]''s descended from a mythical creature', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for the next big opportunity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has an unrequited love for someone unattainable', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to start a new life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a survivor of a deadly virus outbreak', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the lookout for the supernatural', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s haunted by a past mistake', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s physically strong but emotionally fragile', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has a scar that tells a story', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s motivated by revenge', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a master of disguise', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s constantly changing [their] appearance', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always the underdog', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s can''t escape [their] own mind', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a thrill-seeker', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to break a bad habit', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s plagued by nightmares', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s running from [their] own destiny', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always working hard to make a living', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in the shadow of someone else', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a sucker for a good romance', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always putting others before [them]self', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to atone for a terrible mistake', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s seeking vengeance against an enemy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s determined to prove [their] worth', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s constantly underestimated but fiercely determined', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s struggling to overcome a debilitating illness', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in the right place at the right time', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a master of sarcasm and wit', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for the next thrill', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s desperately holding onto a lost love', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s just trying to get by in life', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s been gifted with a unique talent', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s haunted by a traumatic event from [their] childhood', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s constantly searching for a sense of belonging', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s torn between two worlds', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always been a lone wolf', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s chasing after an elusive dream', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the brink of self-destruction', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to escape a life of crime', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s hiding a mysterious past', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in the front lines of battle', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s struggling to forgive [them]self', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s facing insurmountable odds', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to live up to [their] family''s expectations', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the move', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s fighting against [their] own destiny', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s battling a powerful addiction', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s harboring a dangerous obsession', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always searching for the next challenge', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to forget a painful memory', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s living with a heavy heart', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('fighting for redemption', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('haunted by the past', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('hunted by a powerful foe', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('in search of wisdom', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who inherited a mystical artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is lost and searching for purpose', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('marked by destiny', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('on a mission to save [their] people', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('suffering from a rare disease', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('surviving against all odds', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('taken in by a mentor', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('trained in a secret art', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is wandering aimlessly', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('yearning for adventure', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('born under a lucky star', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('born under an unlucky star', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('determined to prove [their] worth', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('facing an impossible choice', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('gifted with extraordinary powers', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('carrying a heavy burden', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('cursed with immortality', '{"compatibleAges": ["adult", "middle-aged", "elderly", "venerable"]}'),
('destined for greatness', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('destined to fail', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('disguised as someone else', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('earning a living through thievery', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('hiding [their] true identity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is hunting a dangerous creature', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('living a double life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('living in constant fear', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('on a quest for vengeance', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is part of a lost civilization', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('preparing for a great battle', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('protecting [their] homeland', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('running from a terrible fate', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('sailing the high seas', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('searching for a lost city', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('seeking revenge for a past betrayal', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('serving [their] country', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('struggling with a moral dilemma', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the chosen one', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the subject of a prophecy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('trained to be a deadly assassin', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('working as a spy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('wielding an ancient weapon', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('working as a sellsword', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('wrangling a dangerous pet', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('yearning for a peaceful life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is becoming a master of [their] craft', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('battling inner demons', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is conquering insurmountable odds', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who inadvertently became a curse-breaker', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a disgraced noble seeking redemption', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('dreaming of a different life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('escaping the fate of [their] family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a guardian of an ancient artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a heir to a powerful kingdom', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('hiding a supernatural identity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is hunting a personal foe', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is hunting the creature that killed someone important', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is losing faith in [their] cause', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('owning and operating a successful business', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is part of a squad of elite soldiers', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a prisoner on the run', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('protecting the balance of nature', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('recovering from a tragic loss', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('seeking to uncover [their] family history', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('selling [their] services to the highest bidder', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('serving a powerful and corrupt ruler', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('stranded in a foreign land', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the last hope of [their] people', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('using [their] powers for personal gain', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('yearning for revenge on an old enemy', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is an unwitting pawn in a greater game', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is on the verge of a breakthrough', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is plagued by chronic pain', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is secretly a werecreature', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is seeking redemption for past mistakes', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is struggling with [their] identity', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the black sheep of the family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the last of [their] kind', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who knows everyone in town', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who learned a dark secret about [their] family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lives on the edge', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lost everything in a tragic event', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lost [their] sense of taste', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who lost [their] sense of touch', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who never gives up', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who never sleeps', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who plays by [their] own rules', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who possesses a rare skill', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who returned from the dead', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who seeks power above all else', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who suffers from claustrophobia', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who suffers from chronic memory loss', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who suffers from intense nightmares', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s had the same nightmare every night since [their] birth', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who survived a natural disaster', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who takes orders from no one', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who talks to animals', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was abandoned as a child', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was born into a life of luxury', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was cursed by a witch', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was disowned by [their] family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was exiled from society', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was forced to flee [their] homeland', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was framed for a crime [they] didn''t commit', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was gifted with incredible powers', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was hunted by a powerful organization', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was imprisoned for years', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was inspired by a childhood hero', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was left for dead in the wilderness', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was never given a chance to succeed', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was once a member of a cult', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was once a notorious pirate', '{"compatibleAges": ["adult", "middle-aged", "elderly", "venerable"]}'),
('who was once a revered leader', '{"compatibleAges": ["adult", "middle-aged", "elderly", "venerable"]}'),
('who was once betrayed by [their] closest friend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was once famous but fell from grace', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was recruited by a secret society', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was saved by a mysterious stranger', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was sent back in time', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was separated from [their] twin at birth', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was taken in by a group of outlaws', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was trained by a legendary warrior', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was turned into a monster', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was victimized by a powerful corporation', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who will do anything to protect [their] loved ones', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who works for an evil organization', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who yearns for adventure and excitement', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s an adrenaline junkie', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s an expert escape artist', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for a quick buck', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s atoning for a past mistake', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s been cursed with immortality', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s constantly on the move', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s haunted by a past trauma', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s immortalized in legend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s known for [their] incredible speed', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s lost in a world foreign to [them]', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was born in another plane of existence', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s seeking inner peace', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a former paladin seeking redemption', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s out for revenge against the government', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s on the run from [their] past', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s searching for [their] true purpose', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s sworn to protect the defenseless', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s terrified of the dark', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s the last hope for [their] people', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to undo a mistake from the past', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s wanted dead or alive', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s working to topple a corrupt regime', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s wracked with guilt over a past mistake', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s crossed paths with fortune', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose deepest desire is to attain power', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who knows the location of a powerful artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who always attracts suspicion', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose family was murdered by a rival clan', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose scars tell a story', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a skilled con artist', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s on a quest to save [their] lost love', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s suffered a great betrayal', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s seeking atonement for past sins', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trained in the deadliest of martial art forms', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s lived a double life for years', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a failed experiment that turned out to be a success', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s imbued with magic energy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s been given a second chance at life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s destined for greatness', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s sworn to protect a sacred artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s betrayed those closest to [them]', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s seeking revenge against a traitor', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trapped between two worlds', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s bound by a powerful spell', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s lost [their] memories in a tragic event', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s the only one who knows a dark secret', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s destined to bring about the apocalypse', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s seeking to restore a disrupted balance in nature', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s been scarred by a great tragedy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose past mistakes haunt [their] every step', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was raised by the undead', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose family heirloom is corrupting [their] soul', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always running late', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s an avid reader', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s never without [their] morning coffee', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s terrible at cooking', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a night owl', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a morning person', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a neat freak', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always losing [their] keys', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always forgetting important dates', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying new recipes', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the latest trend', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s often caught daydreaming', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in the middle of home renovation projects', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for a deal', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always overthinking things', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always working on [their] side hustle', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the go', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a little bit of a perfectionist', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s very organized', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in need of a good night''s sleep', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a game night', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s very sentimental', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always talking about [their] pets', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to make people laugh', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s never without a to-do list', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of DIY projects', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good workout', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for inspiration', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always ready to lend a hand', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s passionate about gardening', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a strict vegetarian', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always running errands', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a board game', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying new restaurants', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of a good bargain', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s often caught singing in the shower', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to save energy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to cut down on waste', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a regular at the local farmer''s market', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to improve [their] skills', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always willing to try something new', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a natural at problem-solving', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to give back to the community', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a little friendly competition', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to simplify [their] life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to stay organized', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always chasing [their] dreams', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a hike', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of the perfect cup of tea', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to improve [their] health', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on top of the latest news and trends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always committed to [their] workout routine', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good book', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on top of [their] appointments and deadlines', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to learn something new', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always ready to lend an ear or give advice', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for creative ways to decorate [their] home', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of thrift stores', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always open to new experiences', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good theatre night', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to save money', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of cozy nights in', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a stroll in the park', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a responsible exotic pet owner', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s an irresponsible exotic pet owner', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who owns way too many cats', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who owns way too many dogs', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who owns way too many pets', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of weekend brunches', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to reduce stress in [their] life', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of the perfect work-life balance', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always interested in learning about different cultures', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for new recipes to try at home', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to improve [their] work skills', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good dance party', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of the perfect cup of coffee', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of volunteering for a good cause', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to stay organized at work', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good karaoke session', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always a stickler for punctuality', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of relaxation and tranquility', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a friendly game of basketball', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good caravan trip', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to keep [their] living space tidy', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of the perfect skincare routine', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a game of chess', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of afternoon naps', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the lookout for the latest fashion trends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good workout class', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to reduce waste in [their] home', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a regular at the nearby wrestling ring', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a talented wrestler', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the hunt for the best sandwich in town', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a walk around the neighborhood', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('blessed by the gods', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('from a cursed family', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who belongs to a secret organization', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is considered the best in [their] profession', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who prefers to work naked', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with a pathetic plastic smile', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('with no regard for the law', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is highly respected in the community', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who eats very healthy after that accident', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is in between jobs', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('whose actions are supervised by a relative', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is at the top of [their] career', '{"compatibleAges": ["adult", "middle-aged", "elderly", "venerable"]}'),
('with biased ideologies', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who suffers from panic attacks', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is skilled in a forgotten art', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who possesses a rare and powerful gift', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in the wrong place at the wrong time', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s searching for meaning in a meaningless world', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s trying to create a better future', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s keeping a dark secret from [their] loved ones', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is the last of [their] kind', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('destined to lead [their] people', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who has sworn to protect the innocent', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who is a gifted artist struggling to make a name for [them]self', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('surviving in a harsh, post-apocalyptic wasteland', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('working [their] way to the top through cunning and charisma', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who seems to have it all figured out, but [their] is just putting on a front', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who was transformed by a magical artifact', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s known for [their] incredible agility', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s in hiding from [their] enemies', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s hunted for what [they] know', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always writing boring letters to [their] friends', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good conversation', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always daydreaming about [their] next vacation', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for ways to stay hydrated', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to stay on top of [their] laundry pile', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always in search of the best way to wind down after work', '{"compatibleAges": ["young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a friendly game of cards', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s a fan of meditation and mindfulness practices', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good art exhibit', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always trying to learn a new language', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always on the hunt for unique jewelry', '{"compatibleAges": ["adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for new and exciting workout routines', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always up for a good camping trip', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who''s always looking for new ways to spice up [their] meals', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who only wears pink clothes', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}'),
('who only wears black clothes', '{"compatibleAges": ["child", "adolescent", "young adult","adult", "middle-aged", "elderly", "venerable"]}');
