openapi: 3.0.3
info:
  title: Monstershuffler API
  description: REST API for monstershuffler.com
  version: 0.0.2
components:
  schemas: {}
paths: {}
servers: []
tags:
  - name: users
    description: "The users' account. "
  - name: backgrounds
    description: Backgrounds are a way to define a character's occupation, like a
      soldier, a merchant, a priest, etc. and give them minor abilities related
      to that occupation. They are usually given to NPCs in place of classes.
  - name: classes
    description: Classes are the main way to define a character's role in the game.
      They define what abilities the character has and how they can use them.
  - name: npcs
    description: Tools to generate non-player-characters (NPCs).
  - name: races
    description: A race defines the innate abilities derived from a character's
      fantasy ancestry.
