import { z } from 'zod';

export const tagsObject = z.object({
  name: z.string(),
  Name: z.string(),
  he: z.string(),
  she: z.string(),
  his: z.string(),
  her: z.string(),
  him: z.string(),
  hers: z.string(),
  He: z.string(),
  His: z.string(),
  Him: z.string(),
  Hers: z.string(),
  they: z.string(),
  their: z.string(),
  them: z.string(),
  theirs: z.string(),
  They: z.string(),
  Their: z.string(),
  Them: z.string(),
  Theirs: z.string(),
  it: z.string(),
  its: z.string(),
  It: z.string(),
  Its: z.string(),
  size: z.string(),
  sizegreater: z.string(),
  sizesmaller: z.string(),
  sizetwogreater: z.string(),
  sizetwosmaller: z.string(),
  type: z.string(),
}).catchall(z.string());
