INSERT INTO characterhooks VALUES 
('blessed with good luck', true, true, true, true, true, true true),
('cursed by the gods', true, true, true, true, true, true true),
('cursed with bad luck', true, true, true, true, true, true true),
('cursed with good luck', true, true, true, true, true, true true),
('escaping the past', false, true, true, true, true, true true),
('from a good family', true, true, true, true, true, true true),
('from a loathed family', true, true, true, true, true, true true),
('from an unusual family line', true, true, true, true, true, true true),
('from nowhere', false, true, true, true, true, true true),
('haunted by dark memories', true, true, true, true, true, true true),
('hiding a dark secret', true, true, true, true, true, true true),
('living on borrowed time', true, true, true, true, true, true true),
('looking for love', true, true, true, true, true, true true),
('needing a friend', true, true, true, true, true, true true),
('on the run from the law', true, true, true, true, true, true true),
('on the wrong side of the law', true, true, true, true, true, true true),
('searching for justice', true, true, true, true, true, true true),
('searching for love', true, true, true, true, true, true true),
('trapped by the past', false, true, true, true, true, true true),
('who can''t resist a fight', true, true, true, true, true, true true),
('who fears people think [they] is a fraud', true, true, true, true, true, true true),
('who fell in with the wrong crowd', true, true, true, true, true, true true),
('who had a near-death experience', true, true, true, true, true, true true),
('who had a near-death experience that changed [them] significantly', true, true, true, true, true, true true),
('who has an alter ego', true, true, true, true, true, true true),
('who has an arch-enemy', true, true, true, true, true, true true),
('who has an odd way of speaking', true, true, true, true, true, true true),
('who hates animals', true, true, true, true, true, true true),
('who hates children', true, true, true, true, true, true true),
('who hates the government', true, true, true, true, true, true true),
('who is a complete fraud', true, true, true, true, true, true true),
('who is a jack of all trades', true, true, true, true, true, true true),
('who is a loose cannon', true, true, true, true, true, true true),
('who is an undercover agent', true, true, true, true, true, true true),
('who is barking up the wrong tree', true, true, true, true, true, true true),
('who is being blackmailed', true, true, true, true, true, true true),
('who is considered the worst in [their] profession', false, true, true, true, true, true true),
('who is dependent on medication', true, true, true, true, true, true true),
('who is estranged from family members', true, true, true, true, true, true true),
('who is given to moments of deep introspection', true, true, true, true, true, true true),
('who is helping the local community', true, true, true, true, true, true true),
('who is just a cog in the machine', true, true, true, true, true, true true),
('who is keeping [their] mouth shut', true, true, true, true, true, true true),
('who is keeping something at bay', true, true, true, true, true, true true),
('who is more than meets the eye', true, true, true, true, true, true true),
('who is prone to odd statements', true, true, true, true, true, true true),
('who is searching for employment', true, true, true, true, true, true true),
('who is struggling between good and evil', true, true, true, true, true, true true),
('who is stubborn as a mule', true, true, true, true, true, true true),
('who is the life and soul of the party', true, true, true, true, true, true true),
('who is thinking of retiring', true, true, true, true, true, true true),
('who is ugly as sin', true, true, true, true, true, true true),
('who lost a close friend', true, true, true, true, true, true true),
('who lost meaning in life', true, true, true, true, true, true true),
('who loves animals', true, true, true, true, true, true true),
('who loves children', false, true, true, true, true, true true),
('who prefers to work alone', false, true, true, true, true, true true),
('who recently betrayed [their] faith', true, true, true, true, true, true true),
('who seems insane', true, true, true, true, true, true true),
('who looks very suspect', true, true, true, true, true, true true),
('who spent part of [their] life in prison', true, true, true, true, true, true true),
('who suffers from a chronic medical condition', true, true, true, true, true, true true),
('with a bright future ahead', true, true, true, true, true, true true),
('with a chemical dependency', false, true, true, true, true, true true),
('with a criminal mind', true, true, true, true, true, true true),
('with a dark past', true, true, true, true, true, true true),
('with a false identity', true, true, true, true, true, true true),
('with a grim future ahead', true, true, true, true, true, true true),
('with a heart of gold', true, true, true, true, true, true true),
('with a knack for trouble', true, true, true, true, true, true true),
('with a lot of friends', true, true, true, true, true, true true),
('with a lovely smile', true, true, true, true, true, true true),
('with a terrible poker face', true, true, true, true, true, true true),
('with a thirst for knowledge', true, true, true, true, true, true true),
('with a thirst for vengeance', true, true, true, true, true, true true),
('with a very tight schedule', true, true, true, true, true, true true),
('with a weird superpower', true, true, true, true, true, true true),
('with an extraordinary wealth', true, true, true, true, true, true true),
('with an obsessive desire for power', true, true, true, true, true, true true),
('with an odd birthmark', true, true, true, true, true, true true),
('with an odd tattoo', false, true, true, true, true, true true),
('with an unexpected destiny', true, true, true, true, true, true true),
('with an unusual child', false, true, true, true, true, true true),
('with an unusual spouse', false, true, true, true, true, true true),
('with big dreams', true, true, true, true, true, true true),
('with little money', true, true, true, true, true, true true),
('with a mental illness', false, true, true, true, true, true true),
('with no friends', true, true, true, true, true, true true),
('with no hope', true, true, true, true, true, true true),
('with repressed memories', true, true, true, true, true, true true),
('with suicidal thoughts', false, true, true, true, true, true true),
('with unconventional clothing', true, true, true, true, true, true true),
('who wants to change the world', true, true, true, true, true, true true),
('whose heart is broken', true, true, true, true, true, true true),
('who wants to redeem [their] family', true, true, true, true, true, true true),
('with a sexy body', false, true, true, true, true, true true),
('with a weird body', true, true, true, true, true, true true),
('who is very famous', true, true, true, true, true, true true),
('who is despised in the community', true, true, true, true, true, true true),
('who can''t read', true, true, true, true, true, true true),
('who wrote a book', true, true, true, true, true, true true),
('who hates the wilderness', true, true, true, true, true, true true),
('who loves the wilderness', true, true, true, true, true, true true),
('who is perfectly normal', true, true, true, true, true, true true),
('with a huge obsession', true, true, true, true, true, true true),
('with an identical twin', true, true, true, true, true, true true),
('with a second family', true, true, true, true, true, true true),
('who was falsely accused of a crime', true, true, true, true, true, true true),
('who gambles a lot', true, true, true, true, true, true true),
('who is a self taught martial artist', true, true, true, true, true, true true),
('who always arrives late', true, true, true, true, true, true true),
('who always arrives early', true, true, true, true, true, true true),
('who thinks [they] saw an alien', true, true, true, true, true, true true),
('whose face is badly scarred', true, true, true, true, true, true true),
('with an animal friend', true, true, true, true, true, true true),
('with a hidden agenda', true, true, true, true, true, true true),
('who is very proud of [their] own race', true, true, true, true, true, true true),
('who refuses to call people by their own name', true, true, true, true, true, true true),
('who only works part-time', false, true, true, true, true, true true),
('who mysteriously wanders at night', true, true, true, true, true, true true),
('who never wears underwear', false, true, true, true, true, true true),
('who is very attached to tradition', true, true, true, true, true, true true),
('who likes to be domineering', true, true, true, true, true, true true),
('with a very successful business', true, true, true, true, true, true true),
('with an unsuccessful business', true, true, true, true, true, true true),
('who fought in a war', false, true, true, true, true, true true),
('who only wants to feel appreciated', true, true, true, true, true, true true),
('who hates crowds', true, true, true, true, true, true true),
('who does daily workouts', true, true, true, true, true, true true),
('who will never be as good as [their] predecessor', true, true, true, true, true, true true),
('who outclasses [their] predecessor', true, true, true, true, true, true true),
('with a tyrannical master', true, true, true, true, true, true true),
('with a boring life', true, true, true, true, true, true true),
('with a conventional life', true, true, true, true, true, true true),
('with a secret romantic relationship', false, true, true, true, true, true true),
('who schemes in the shadows', true, true, true, true, true, true true),
('with a best friend from far away', true, true, true, true, true, true true),
('who is an adventurer for hire', false, true, true, true, true, true true),
('who was adopted', true, true, true, true, true, true true),
('who takes care of [their] family', true, true, true, true, true, true true),
('who is a talented singer', true, true, true, true, true, true true),
('with three parents', true, true, true, true, true, true true),
('who recently lost a close friend', true, true, true, true, true, true true),
('with a childhood trauma', true, true, true, true, true, true true),
('who travels a lot', true, true, true, true, true, true true),
('who almost never leaves [their] house', true, true, true, true, true, true true),
('who believes in strange conspiracy theories', true, true, true, true, true, true true),
('who grows [their] own food', true, true, true, true, true, true true),
('with a hoarding disorder', true, true, true, true, true, true true),
('with a lot of issues', true, true, true, true, true, true true),
('who is an expert in astrology', true, true, true, true, true, true true),
('who designs [their] own clothes', true, true, true, true, true, true true),
('who lives inside [their] head', true, true, true, true, true, true true),
('who likes to have guests', true, true, true, true, true, true true),
('who hates foreigners', true, true, true, true, true, true true),
('who has been publicly shamed', true, true, true, true, true, true true),
('who is admired by many', true, true, true, true, true, true true),
('who is very old fashioned', true, true, true, true, true, true true),
('who embraces innovation', true, true, true, true, true, true true),
('who is afraid of death', true, true, true, true, true, true true),
('who believes in destiny', true, true, true, true, true, true true),
('who loves to give public speeches', true, true, true, true, true, true true),
('who drinks a lot', false, false, true, true, true, true true),
('with sinister morals', true, true, true, true, true, true true),
('with pure thoughts', true, true, true, true, true, true true),
('who endeavors to solve philosophical dilemmas', true, true, true, true, true, true true),
('with gastrointestinal issues', true, true, true, true, true, true true),
('with political ambitions', true, true, true, true, true, true true),
('who admires a local hero', true, true, true, true, true, true true),
('who can''t control [them]self', true, true, true, true, true, true true),
('who is very perverted', false, false, true, true, true, true true),
('who got married more than once', false, false, false, true, true, true true),
('from a privileged family', true, true, true, true, true, true true),
('who recently moved to a new house', true, true, true, true, true, true true),
('who unintentionally hurt someone', true, true, true, true, true, true true),
('who is also a collectionist', true, true, true, true, true, true true),
('with lots of jewelry', true, true, true, true, true, true true),
('who has witnessed a crime', true, true, true, true, true, true true),
('who was promised wealth and fame', true, true, true, true, true, true true),
('who goes on vacation often', true, true, true, true, true, true true),
('with a deadly allergy', true, true, true, true, true, true true),
('with a valuable family heirloom', true, true, true, true, true, true true),
('who cares for the environment', true, true, true, true, true, true true),
('who doesn''t care for the environment', true, true, true, true, true, true true),
('who is really a robot in disguise', true, true, true, true, true, true true),
('who is seeking redemption', true, true, true, true, true, true true),
('who is silently judging everyone', true, true, true, true, true, true true),
('who is struggling with addiction', false, true, true, true, true, true true),
('who is the black sheep of the family', true, true, true, true, true, true true),
('who is the last of [their] kind', true, true, true, true, true, true true),
('who is the only survivor of a tragedy', true, true, true, true, true, true true),
('who is the victim of mistaken identity', true, true, true, true, true, true true),
('who is trying to make amends', true, true, true, true, true, true true),
('who is unsure of [their] true identity', true, true, true, true, true, true true),
('who is wanted dead or alive', true, true, true, true, true, true true),
('who keeps having prophetic dreams', true, true, true, true, true, true true),
('who left everything behind to pursue a dream', false, true, true, true, true, true true),
('who lost everything in a natural disaster', true, true, true, true, true, true true),
('who made a deal with the devil', true, true, true, true, true, true true),
('who never backs down from a challenge', true, true, true, true, true, true true),
('who never forgets a face', true, true, true, true, true, true true),
('who never speaks the truth', true, true, true, true, true, true true),
('who ran away from home at a young age', false, true, true, true, true, true true),
('who sees ghosts', true, true, true, true, true, true true),
('who seeks revenge for a past betrayal', true, true, true, true, true, true true),
('who seems average but has a hidden talent', true, true, true, true, true, true true),
('who talks to imaginary friends', true, true, true, true, true, true true),
('who was abandoned as a child', false, true, true, true, true, true true),
('who was betrayed by someone [they] trusted', true, true, true, true, true, true true),
('who was once a hero but now a villain', false, false, true, true, true, true true),
('who was once wealthy but lost everything', true, true, true, true, true, true true),
('who wishes to be immortal', true, true, true, true, true, true true),
('who''s always on the lookout for danger', true, true, true, true, true, true true),
('who''s constantly plagued with bad luck', true, true, true, true, true, true true),
('who''s haunted by the ghosts of [their] enemies', true, true, true, true, true, true true),
('who''s known for [their] terrible cooking', false, true, true, true, true, true true),
('who''s searching for a lost artifact', true, true, true, true, true, true true),
('who''s seeking [their] true purpose', true, true, true, true, true, true true),
('who struggles with social anxiety', true, true, true, true, true, true true),
('who possesses a mysterious and ancient artifact', true, true, true, true, true, true true),
('who''s on a quest for knowledge', true, true, true, true, true, true true),
('who has a love-hate relationship with [their] powers', true, true, true, true, true, true true),
('who believes [they]''s descended from a mythical creature', true, true, true, true, true, true true),
('who''s always looking for the next big opportunity', true, true, true, true, true, true true),
('who has an unrequited love for someone unattainable', true, true, true, true, true, true true),
('who''s trying to start a new life', true, true, true, true, true, true true),
('who''s a survivor of a deadly virus outbreak', true, true, true, true, true, true true),
('who''s always on the lookout for the supernatural', true, true, true, true, true, true true),
('who''s haunted by a past mistake', true, true, true, true, true, true true),
('who''s physically strong but emotionally fragile', true, true, true, true, true, true true),
('who has a scar that tells a story', true, true, true, true, true, true true),
('who''s motivated by revenge', true, true, true, true, true, true true),
('who''s a master of disguise', true, true, true, true, true, true true),
('who''s constantly changing [their] appearance', true, true, true, true, true, true true),
('who''s always the underdog', true, true, true, true, true, true true),
('who''s can''t escape [their] own mind', true, true, true, true, true, true true),
('who''s a thrill-seeker', true, true, true, true, true, true true),
('who''s trying to break a bad habit', true, true, true, true, true, true true),
('who''s plagued by nightmares', true, true, true, true, true, true true),
('who''s running from [their] own destiny', true, true, true, true, true, true true),
('who''s always working hard to make a living', false, true, true, true, true, true true),
('who''s always in the shadow of someone else', true, true, true, true, true, true true),
('who''s a sucker for a good romance', false, true, true, true, true, true true),
('who''s always putting others before [them]self', true, true, true, true, true, true true),
('who''s trying to atone for a terrible mistake', true, true, true, true, true, true true),
('who''s seeking vengeance against an enemy', true, true, true, true, true, true true),
('who''s determined to prove [their] worth', true, true, true, true, true, true true),
('who''s constantly underestimated but fiercely determined', true, true, true, true, true, true true),
('who''s struggling to overcome a debilitating illness', true, true, true, true, true, true true),
('who''s always in the right place at the right time', true, true, true, true, true, true true),
('who''s a master of sarcasm and wit', true, true, true, true, true, true true),
('who''s always looking for the next thrill', true, true, true, true, true, true true),
('who''s desperately holding onto a lost love', true, true, true, true, true, true true),
('who''s just trying to get by in life', false, true, true, true, true, true true),
('who''s been gifted with a unique talent', true, true, true, true, true, true true),
('who''s haunted by a traumatic event from [their] childhood', false, true, true, true, true, true true),
('who''s constantly searching for a sense of belonging', true, true, true, true, true, true true),
('who''s torn between two worlds', true, true, true, true, true, true true),
('who''s always been a lone wolf', false, true, true, true, true, true true),
('who''s chasing after an elusive dream', true, true, true, true, true, true true),
('who''s always on the brink of self-destruction', true, true, true, true, true, true true),
('who''s trying to escape a life of crime', true, true, true, true, true, true true),
('who''s hiding a mysterious past', true, true, true, true, true, true true),
('who''s always in the front lines of battle', false, false, true, true, true, true true),
('who''s struggling to forgive [them]self', true, true, true, true, true, true true),
('who''s facing insurmountable odds', true, true, true, true, true, true true),
('who''s trying to live up to [their] family''s expectations', true, true, true, true, true, true true),
('who''s always on the move', true, true, true, true, true, true true),
('who''s fighting against [their] own destiny', true, true, true, true, true, true true),
('who''s battling a powerful addiction', false, true, true, true, true, true true),
('who''s harboring a dangerous obsession', true, true, true, true, true, true true),
('who''s always searching for the next challenge', true, true, true, true, true, true true),
('who''s trying to forget a painful memory', true, true, true, true, true, true true),
('who''s living with a heavy heart', true, true, true, true, true, true true),
('fighting for redemption', true, true, true, true, true, true true),
('haunted by the past', true, true, true, true, true, true true),
('hunted by a powerful foe', true, true, true, true, true, true true),
('in search of wisdom', true, true, true, true, true, true true),
('who inherited a mystical artifact', true, true, true, true, true, true true),
('who is lost and searching for purpose', false, true, true, true, true, true true),
('marked by destiny', true, true, true, true, true, true true),
('on a mission to save [their] people', true, true, true, true, true, true true),
('suffering from a rare disease', true, true, true, true, true, true true),
('surviving against all odds', true, true, true, true, true, true true),
('taken in by a mentor', true, true, true, true, true, true true),
('trained in a secret art', true, true, true, true, true, true true),
('who is wandering aimlessly', true, true, true, true, true, true true),
('yearning for adventure', true, true, true, true, true, true true),
('born under a lucky star', true, true, true, true, true, true true),
('born under an unlucky star', true, true, true, true, true, true true),
('determined to prove [their] worth', true, true, true, true, true, true true),
('facing an impossible choice', true, true, true, true, true, true true),
('gifted with extraordinary powers', true, true, true, true, true, true true),
('carrying a heavy burden', true, true, true, true, true, true true),
('cursed with immortality', false, false, false, true, true, true true),
('destined for greatness', true, true, true, true, true, true true),
('destined to fail', true, true, true, true, true, true true),
('disguised as someone else', true, true, true, true, true, true true),
('earning a living through thievery', true, true, true, true, true, true true),
('hiding [their] true identity', true, true, true, true, true, true true),
('who is hunting a dangerous creature', true, true, true, true, true, true true),
('living a double life', true, true, true, true, true, true true),
('living in constant fear', true, true, true, true, true, true true),
('on a quest for vengeance', true, true, true, true, true, true true),
('who is part of a lost civilization', true, true, true, true, true, true true),
('preparing for a great battle', false, true, true, true, true, true true),
('protecting [their] homeland', true, true, true, true, true, true true),
('running from a terrible fate', true, true, true, true, true, true true),
('sailing the high seas', true, true, true, true, true, true true),
('searching for a lost city', true, true, true, true, true, true true),
('seeking revenge for a past betrayal', true, true, true, true, true, true true),
('serving [their] country', true, true, true, true, true, true true),
('struggling with a moral dilemma', true, true, true, true, true, true true),
('who is the chosen one', true, true, true, true, true, true true),
('who is the subject of a prophecy', true, true, true, true, true, true true),
('trained to be a deadly assassin', false, true, true, true, true, true true),
('working as a spy', true, true, true, true, true, true true),
('wielding an ancient weapon', true, true, true, true, true, true true),
('working as a sellsword', false, true, true, true, true, true true),
('wrangling a dangerous pet', true, true, true, true, true, true true),
('yearning for a peaceful life', true, true, true, true, true, true true),
('who is becoming a master of [their] craft', false, true, true, true, true, true true),
('battling inner demons', true, true, true, true, true, true true),
('who is conquering insurmountable odds', true, true, true, true, true, true true),
('who inadvertently became a curse-breaker', true, true, true, true, true, true true),
('who is a disgraced noble seeking redemption', true, true, true, true, true, true true),
('dreaming of a different life', true, true, true, true, true, true true),
('escaping the fate of [their] family', true, true, true, true, true, true true),
('who is a guardian of an ancient artifact', true, true, true, true, true, true true),
('who is a heir to a powerful kingdom', true, true, true, true, true, true true),
('hiding a supernatural identity', true, true, true, true, true, true true),
('who is hunting a personal foe', true, true, true, true, true, true true),
('who is hunting the creature that killed someone important', true, true, true, true, true, true true),
('who is losing faith in [their] cause', true, true, true, true, true, true true),
('owning and operating a successful business', true, true, true, true, true, true true),
('who is part of a squad of elite soldiers', false, false, true, true, true, true true),
('who is a prisoner on the run', false, true, true, true, true, true true),
('protecting the balance of nature', true, true, true, true, true, true true),
('recovering from a tragic loss', true, true, true, true, true, true true),
('seeking to uncover [their] family history', true, true, true, true, true, true true),
('selling [their] services to the highest bidder', false, true, true, true, true, true true),
('serving a powerful and corrupt ruler', true, true, true, true, true, true true),
('stranded in a foreign land', true, true, true, true, true, true true),
('who is the last hope of [their] people', true, true, true, true, true, true true),
('using [their] powers for personal gain', false, true, true, true, true, true true),
('yearning for revenge on an old enemy', false, true, true, true, true, true true),
('who is an unwitting pawn in a greater game', true, true, true, true, true, true true),
('who is on the verge of a breakthrough', false, true, true, true, true, true true),
('who is plagued by chronic pain', false, true, true, true, true, true true),
('who is secretly a werecreature', true, true, true, true, true, true true),
('who is seeking redemption for past mistakes', true, true, true, true, true, true true),
('who is struggling with [their] identity', true, true, true, true, true, true true),
('who is the black sheep of the family', true, true, true, true, true, true true),
('who is the last of [their] kind', true, true, true, true, true, true true),
('who knows everyone in town', true, true, true, true, true, true true),
('who learned a dark secret about [their] family', true, true, true, true, true, true true),
('who lives on the edge', false, true, true, true, true, true true),
('who lost everything in a tragic event', true, true, true, true, true, true true),
('who lost [their] sense of taste', true, true, true, true, true, true true),
('who lost [their] sense of touch', true, true, true, true, true, true true),
('who never gives up', true, true, true, true, true, true true),
('who never sleeps', true, true, true, true, true, true true),
('who plays by [their] own rules', true, true, true, true, true, true true),
('who possesses a rare skill', true, true, true, true, true, true true),
('who returned from the dead', true, true, true, true, true, true true),
('who seeks power above all else', true, true, true, true, true, true true),
('who suffers from claustrophobia', true, true, true, true, true, true true),
('who suffers from chronic memory loss', true, true, true, true, true, true true),
('who suffers from intense nightmares', true, true, true, true, true, true true),
('who''s had the same nightmare every night since [their] birth', true, true, true, true, true, true true),
('who survived a natural disaster', true, true, true, true, true, true true),
('who takes orders from no one', true, true, true, true, true, true true),
('who talks to animals', true, true, true, true, true, true true),
('who was abandoned as a child', false, true, true, true, true, true true),
('who was born into a life of luxury', true, true, true, true, true, true true),
('who was cursed by a witch', true, true, true, true, true, true true),
('who was disowned by [their] family', true, true, true, true, true, true true),
('who was exiled from society', false, true, true, true, true, true true),
('who was forced to flee [their] homeland', true, true, true, true, true, true true),
('who was framed for a crime [they] didn''t commit', true, true, true, true, true, true true),
('who was gifted with incredible powers', true, true, true, true, true, true true),
('who was hunted by a powerful organization', true, true, true, true, true, true true),
('who was imprisoned for years', false, true, true, true, true, true true),
('who was inspired by a childhood hero', true, true, true, true, true, true true),
('who was left for dead in the wilderness', true, true, true, true, true, true true),
('who was never given a chance to succeed', false, true, true, true, true, true true),
('who was once a member of a cult', false, true, true, true, true, true true),
('who was once a notorious pirate', false, false, false, true, true, true true),
('who was once a revered leader', false, false, false, true, true, true true),
('who was once betrayed by [their] closest friend', true, true, true, true, true, true true),
('who was once famous but fell from grace', false, true, true, true, true, true true),
('who was recruited by a secret society', false, true, true, true, true, true true),
('who was saved by a mysterious stranger', true, true, true, true, true, true true),
('who was sent back in time', true, true, true, true, true, true true),
('who was separated from [their] twin at birth', true, true, true, true, true, true true),
('who was taken in by a group of outlaws', true, true, true, true, true, true true),
('who was trained by a legendary warrior', false, true, true, true, true, true true),
('who was turned into a monster', false, true, true, true, true, true true),
('who was victimized by a powerful corporation', true, true, true, true, true, true true),
('who will do anything to protect [their] loved ones', true, true, true, true, true, true true),
('who works for an evil organization', true, true, true, true, true, true true),
('who yearns for adventure and excitement', true, true, true, true, true, true true),
('who''s an adrenaline junkie', true, true, true, true, true, true true),
('who''s an expert escape artist', true, true, true, true, true, true true),
('who''s always looking for a quick buck', true, true, true, true, true, true true),
('who''s atoning for a past mistake', true, true, true, true, true, true true),
('who''s been cursed with immortality', true, true, true, true, true, true true),
('who''s constantly on the move', true, true, true, true, true, true true),
('who''s haunted by a past trauma', true, true, true, true, true, true true),
('who''s immortalized in legend', true, true, true, true, true, true true),
('who''s known for [their] incredible speed', true, true, true, true, true, true true),
('who''s lost in a world foreign to [them]', true, true, true, true, true, true true),
('who was born in another plane of existence', true, true, true, true, true, true true),
('who''s seeking inner peace', true, true, true, true, true, true true),
('who''s a former paladin seeking redemption', false, false, true, true, true, true true),
('who''s out for revenge against the government', true, true, true, true, true, true true),
('who''s on the run from [their] past', false, true, true, true, true, true true),
('who''s searching for [their] true purpose', true, true, true, true, true, true true),
('who''s sworn to protect the defenseless', true, true, true, true, true, true true),
('who''s terrified of the dark', true, true, true, true, true, true true),
('who''s the last hope for [their] people', true, true, true, true, true, true true),
('who''s trying to undo a mistake from the past', true, true, true, true, true, true true),
('who''s wanted dead or alive', false, true, true, true, true, true true),
('who''s working to topple a corrupt regime', true, true, true, true, true, true true),
('who''s wracked with guilt over a past mistake', true, true, true, true, true, true true),
('who''s crossed paths with fortune', true, true, true, true, true, true true),
('whose deepest desire is to attain power', true, true, true, true, true, true true),
('who knows the location of a powerful artifact', true, true, true, true, true, true true),
('who always attracts suspicion', true, true, true, true, true, true true),
('whose family was murdered by a rival clan', true, true, true, true, true, true true),
('whose scars tell a story', true, true, true, true, true, true true),
('who''s a skilled con artist', true, true, true, true, true, true true),
('who''s on a quest to save [their] lost love', false, true, true, true, true, true true),
('who''s suffered a great betrayal', false, true, true, true, true, true true),
('who''s seeking atonement for past sins', true, true, true, true, true, true true),
('who''s trained in the deadliest of martial art forms', false, true, true, true, true, true true),
('who''s lived a double life for years', false, true, true, true, true, true true),
('who''s a failed experiment that turned out to be a success', true, true, true, true, true, true true),
('who''s imbued with magic energy', true, true, true, true, true, true true),
('who''s been given a second chance at life', true, true, true, true, true, true true),
('who''s destined for greatness', true, true, true, true, true, true true),
('who''s sworn to protect a sacred artifact', true, true, true, true, true, true true),
('who''s betrayed those closest to [them]', false, true, true, true, true, true true),
('who''s seeking revenge against a traitor', false, true, true, true, true, true true),
('who''s trapped between two worlds', true, true, true, true, true, true true),
('who''s bound by a powerful spell', true, true, true, true, true, true true),
('who''s lost [their] memories in a tragic event', true, true, true, true, true, true true),
('who''s the only one who knows a dark secret', true, true, true, true, true, true true),
('who''s destined to bring about the apocalypse', true, true, true, true, true, true true),
('who''s seeking to restore a disrupted balance in nature', true, true, true, true, true, true true),
('who''s been scarred by a great tragedy', true, true, true, true, true, true true),
('whose past mistakes haunt [their] every step', false, false, true, true, true, true true),
('who was raised by the undead', true, true, true, true, true, true true),
('whose family heirloom is corrupting [their] soul', true, true, true, true, true, true true),
('who''s always running late', true, true, true, true, true, true true),
('who''s an avid reader', true, true, true, true, true, true true),
('who''s never without [their] morning coffee', false, true, true, true, true, true true),
('who''s terrible at cooking', false, true, true, true, true, true true),
('who''s a night owl', true, true, true, true, true, true true),
('who''s a morning person', true, true, true, true, true, true true),
('who''s a neat freak', true, true, true, true, true, true true),
('who''s always losing [their] keys', true, true, true, true, true, true true),
('who''s always forgetting important dates', false, true, true, true, true, true true),
('who''s always trying new recipes', false, true, true, true, true, true true),
('who''s always on the latest trend', true, true, true, true, true, true true),
('who''s often caught daydreaming', true, true, true, true, true, true true),
('who''s always in the middle of home renovation projects', false, false, true, true, true, true true),
('who''s always looking for a deal', false, true, true, true, true, true true),
('who''s always overthinking things', true, true, true, true, true, true true),
('who''s always working on [their] side hustle', false, true, true, true, true, true true),
('who''s always on the go', true, true, true, true, true, true true),
('who''s a little bit of a perfectionist', true, true, true, true, true, true true),
('who''s very organized', true, true, true, true, true, true true),
('who''s always in need of a good night''s sleep', true, true, true, true, true, true true),
('who''s always up for a game night', false, true, true, true, true, true true),
('who''s very sentimental', true, true, true, true, true, true true),
('who''s always talking about [their] pets', true, true, true, true, true, true true),
('who''s always trying to make people laugh', true, true, true, true, true, true true),
('who''s never without a to-do list', false, true, true, true, true, true true),
('who''s a fan of DIY projects', false, false, true, true, true, true true),
('who''s always up for a good workout', true, true, true, true, true, true true),
('who''s always looking for inspiration', true, true, true, true, true, true true),
('who''s always ready to lend a hand', true, true, true, true, true, true true),
('who''s passionate about gardening', true, true, true, true, true, true true),
('who''s a strict vegetarian', true, true, true, true, true, true true),
('who''s always running errands', true, true, true, true, true, true true),
('who''s always up for a board game', true, true, true, true, true, true true),
('who''s always trying new restaurants', false, true, true, true, true, true true),
('who''s always in search of a good bargain', false, true, true, true, true, true true),
('who''s often caught singing in the shower', true, true, true, true, true, true true),
('who''s always looking for ways to save energy', true, true, true, true, true, true true),
('who''s always trying to cut down on waste', true, true, true, true, true, true true),
('who''s a regular at the local farmer''s market', true, true, true, true, true, true true),
('who''s always trying to improve [their] skills', true, true, true, true, true, true true),
('who''s always willing to try something new', true, true, true, true, true, true true),
('who''s a natural at problem-solving', true, true, true, true, true, true true),
('who''s always looking for ways to give back to the community', true, true, true, true, true, true true),
('who''s always up for a little friendly competition', true, true, true, true, true, true true),
('who''s always looking for ways to simplify [their] life', true, true, true, true, true, true true),
('who''s always looking for ways to stay organized', true, true, true, true, true, true true),
('who''s always chasing [their] dreams', true, true, true, true, true, true true),
('who''s always up for a hike', true, true, true, true, true, true true),
('who''s always in search of the perfect cup of tea', false, true, true, true, true, true true),
('who''s always looking for ways to improve [their] health', false, true, true, true, true, true true),
('who''s always on top of the latest news and trends', true, true, true, true, true, true true),
('who''s always committed to [their] workout routine', true, true, true, true, true, true true),
('who''s always up for a good book', true, true, true, true, true, true true),
('who''s always on top of [their] appointments and deadlines', true, true, true, true, true, true true),
('who''s always trying to learn something new', true, true, true, true, true, true true),
('who''s always ready to lend an ear or give advice', true, true, true, true, true, true true),
('who''s always looking for creative ways to decorate [their] home', true, true, true, true, true, true true),
('who''s a fan of thrift stores', true, true, true, true, true, true true),
('who''s always open to new experiences', true, true, true, true, true, true true),
('who''s always up for a good theatre night', true, true, true, true, true, true true),
('who''s always looking for ways to save money', true, true, true, true, true, true true),
('who''s a fan of cozy nights in', true, true, true, true, true, true true),
('who''s always up for a stroll in the park', true, true, true, true, true, true true),
('who''s a responsible exotic pet owner', true, true, true, true, true, true true),
('who''s an irresponsible exotic pet owner', true, true, true, true, true, true true),
('who owns way too many cats', true, true, true, true, true, true true),
('who owns way too many dogs', true, true, true, true, true, true true),
('who owns way too many pets', true, true, true, true, true, true true),
('who''s a fan of weekend brunches', false, true, true, true, true, true true),
('who''s always trying to reduce stress in [their] life', true, true, true, true, true, true true),
('who''s always in search of the perfect work-life balance', true, true, true, true, true, true true),
('who''s always interested in learning about different cultures', true, true, true, true, true, true true),
('who''s always looking for new recipes to try at home', false, true, true, true, true, true true),
('who''s always trying to improve [their] work skills', false, true, true, true, true, true true),
('who''s always up for a good dance party', true, true, true, true, true, true true),
('who''s always in search of the perfect cup of coffee', false, true, true, true, true, true true),
('who''s a fan of volunteering for a good cause', true, true, true, true, true, true true),
('who''s always looking for ways to stay organized at work', false, true, true, true, true, true true),
('who''s always up for a good karaoke session', true, true, true, true, true, true true),
('who''s always a stickler for punctuality', true, true, true, true, true, true true),
('who''s always in search of relaxation and tranquility', true, true, true, true, true, true true),
('who''s always up for a friendly game of basketball', true, true, true, true, true, true true),
('who''s always up for a good caravan trip', true, true, true, true, true, true true),
('who''s always trying to keep [their] living space tidy', true, true, true, true, true, true true),
('who''s always in search of the perfect skincare routine', false, true, true, true, true, true true),
('who''s always up for a game of chess', true, true, true, true, true, true true),
('who''s a fan of afternoon naps', true, true, true, true, true, true true),
('who''s always on the lookout for the latest fashion trends', true, true, true, true, true, true true),
('who''s always up for a good workout class', true, true, true, true, true, true true),
('who''s always looking for ways to reduce waste in [their] home', true, true, true, true, true, true true),
('who''s a regular at the nearby wrestling ring', true, true, true, true, true, true true),
('who''s a talented wrestler', true, true, true, true, true, true true),
('who''s always on the hunt for the best sandwich in town', true, true, true, true, true, true true),
('who''s always up for a walk around the neighborhood', true, true, true, true, true, true true),
('blessed by the gods', true, true, true, true, true, true true),
('from a cursed family', true, true, true, true, true, true true),
('who belongs to a secret organization', true, true, true, true, true, true true),
('who is considered the best in [their] profession', true, true, true, true, true, true true),
('who prefers to work naked', false, false, true, true, true, true true),
('with a pathetic plastic smile', true, true, true, true, true, true true),
('with no regard for the law', true, true, true, true, true, true true),
('who is highly respected in the community', true, true, true, true, true, true true),
('who eats very healthy after that accident', true, true, true, true, true, true true),
('who is in between jobs', true, true, true, true, true, true true),
('whose actions are supervised by a relative', true, true, true, true, true, true true),
('who is at the top of [their] career', false, false, false, true, true, true true),
('with biased ideologies', true, true, true, true, true, true true),
('who suffers from panic attacks', true, true, true, true, true, true true),
('who is skilled in a forgotten art', false, true, true, true, true, true true),
('who possesses a rare and powerful gift', true, true, true, true, true, true true),
('who''s always in the wrong place at the wrong time', true, true, true, true, true, true true),
('who''s searching for meaning in a meaningless world', true, true, true, true, true, true true),
('who''s trying to create a better future', true, true, true, true, true, true true),
('who''s keeping a dark secret from [their] loved ones', true, true, true, true, true, true true),
('who is the last of [their] kind', true, true, true, true, true, true true),
('destined to lead [their] people', true, true, true, true, true, true true),
('who has sworn to protect the innocent', true, true, true, true, true, true true),
('who is a gifted artist struggling to make a name for [them]self', false, true, true, true, true, true true),
('surviving in a harsh, post-apocalyptic wasteland', true, true, true, true, true, true true),
('working [their] way to the top through cunning and charisma', false, true, true, true, true, true true),
('who seems to have it all figured out, but [their] is just putting on a front', true, true, true, true, true, true true),
('who was transformed by a magical artifact', true, true, true, true, true, true true),
('who''s known for [their] incredible agility', true, true, true, true, true, true true),
('who''s in hiding from [their] enemies', true, true, true, true, true, true true),
('who''s hunted for what [they] know', true, true, true, true, true, true true),
('who''s always writing boring letters to [their] friends', true, true, true, true, true, true true),
('who''s always up for a good conversation', true, true, true, true, true, true true),
('who''s always daydreaming about [their] next vacation', true, true, true, true, true, true true),
('who''s always looking for ways to stay hydrated', true, true, true, true, true, true true),
('who''s always trying to stay on top of [their] laundry pile', false, true, true, true, true, true true),
('who''s always in search of the best way to wind down after work', false, false, true, true, true, true true),
('who''s always up for a friendly game of cards', true, true, true, true, true, true true),
('who''s a fan of meditation and mindfulness practices', true, true, true, true, true, true true),
('who''s always up for a good art exhibit', true, true, true, true, true, true true),
('who''s always trying to learn a new language', true, true, true, true, true, true true),
('who''s always on the hunt for unique jewelry', false, true, true, true, true, true true),
('who''s always looking for new and exciting workout routines', true, true, true, true, true, true true),
('who''s always up for a good camping trip', true, true, true, true, true, true true),
('who''s always looking for new ways to spice up [their] meals', true, true, true, true, true, true true),
('who only wears pink clothes', true, true, true, true, true, true true),
('who only wears black clothes', true, true, true, true, true, true true);
